# Generated by Django 3.2.11 on 2023-06-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_forum_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='forum',
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(default='Default Description', max_length=255),
        ),
    ]
